version: '3.9'

services: 
    pg: 
      image: postgres:15.14-alpine
      container_name: "postgres"
      environment:
        POSTGRES_DB: "orderserv_db"
        POSTGRES_PASSWORD: "12345678"
        POSTGRES_USER: "orderserv"
      volumes:
        - postgres-data:/var/lib/postgresql/data
        - ../db/migrations/order-api/0001_init.sql:/docker-entrypoint-initdb.d/01-order.sql
        - ../db/migrations/inventory-svc/0001_init.sql:/docker-entrypoint-initdb.d/02-inventory.sql
      ports:
        - "127.0.0.1:5432:5432"
      restart: unless-stopped
volumes:       
    postgres-data: